### ISSUE TITLE
Led Visulizer mid offset 

### ISSUE THREAD

**Issue by LostiLama** [naztronaut/dancyPi-audio-reactive-led#46]
Hello my led strip is on the wall and the roof like that   ┐  and i want that  __________   __________
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀I
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀I

here is the mid and not ________________     ___      here  i use the Spectrum LG
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ I
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ I

**Comment by naztronaut** [comment]
That's gonna be a little bit tricky. One way around it is to mess with the number of LEDs. if you add more LEDs, the center will shift where the middle is. Try it out and see if it works. 

If you want to change it programmatically, then it'll be much harder since there's division involved to find the midpoint.

**Comment by LostiLama** [comment]
all good now i dosnt need it any more thanks
